CREATE DATABASE mfaapp;
USE mfaapp;
CREATE TABLE user (
    uid INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(64) UNIQUE NOT NULL,
    name VARCHAR(500) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
);